version: '3'
services:
  application1:
    image: 'spring-boot-metrics-example:latest'
    ports:
      - '8080:8080'
    environment:
      - applicationName=application1
  application2:
    image: 'nginx:latest'
    ports:
      - '8081:80'
  prometheus:
    image: 'prom/prometheus:latest'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
