global:
  scrape_interval: 5s
scrape_configs:
  - job_name: 'application1'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'application1:8080' ]
        labels:
          application: 'springbootify'
